### ISSUE TITLE
REGISTRIERUNG: Anpassung am Registrierungsformular

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#101]
Umsetzung via Issue #117

Folgende Anpassungen an der Registrierungsseite für die SWW.
* Anstatt «Speichern», «Anmelden»
* Im Titel (Registrierung zu Benutzerkonto alte Webseite) möchten wir gerne folgenden Text «Registrieren Sie sich, um einen Account zu erstellen» (Account = Gruppenname)

Wir würden gerne folgende Angaben abfragen:
* E-Mail *  -> speichern in Haupt-E-Mail 
* Anrede* -> Als Dropdown speichern in Geschlecht. Auswahl: Frau, Herr, Andere
* Vorname*
* Nachname*
* Strasse -> speichern in Adresse
* Hausnummer -> speichern in Adresse
* PLZ
*  Ort
*  Geburtsdatum

Das Feld Übername streichen.
Felder mit * sind Pflichfelder und müssen ausgefüllt werden. 

Unter den Anmeldeangaben sollte noch folgender Hinweis stehen: «Indem du auf „Registrieren“ klickst, stimmst du den[ Nutzungsbedingungen](https://www.schweizer-wanderwege.ch/nutzungsbedingungen) der Schweizer Wanderwege zu.

Weitere Informationen darüber, wie die Schweizer Wanderwege deine personenbezogenen Daten erfassen, verwenden, weitergeben und schützen, findest du in der[ Datenschutzrichtlinie der](https://www.schweizer-wanderwege.ch/datenschutz) Schweizer Wanderwege.»

Auf der Anmeldeseite sollte noch ein Link auf die Registrierung führen. «Kein Account? Registrieren Sie sich hier.
![image](https://user-images.githubusercontent.com/9592347/216647824-63c16057-b952-4c0f-8978-3dfed700f58f.png)

# Offene Fragen
- Was ist gemeint mit "Registrierung zu Benutzerkonto alte Webseite"? Dieser Text steht auf hitobito nirgends. Ist mit dem "Titel" der Titel auf dem Browsertab gemeint? Oder ein Heading-Text auf dem Registrierungsformular selber?
    -   Aktuell gibt es h1 Header auf dem Formular. Siehe https://sww.puzzle.ch/de/groups/217/self_registration.  
- Ich nehme an der Nutzungsbedingungen-Text sollte von "Indem du auf „Anmelden“ klickst" sprechen, nicht von „Registrieren“, weil der Button extra auf "Anmelden" geändert wird oder?
    - Button und Text sollte "Anmelden" sein
- Was ist der korrekte Link zu den Nutzungsbedingungen und den Datenschutzrichtlinien? Muss dieser von den SWW-Admins änderbar sein oder ist das immer ein fixer Link?
    - Links sind im Ticket auf SWW angepasst. Text und Links fix, jedoch via Transifex übersetztbar sein:
    schweizer-wanderwege.ch/nutzungsbedingungen, suisse-rando.ch/conditionsdutilisation, sentieri-svizzeri.ch/condizionidiutilizzo
    schweizer-wanderwege.ch/datenschutz, suisse-rando.ch/protectiondesdonnees, sentieri-svizzeri.ch/protezionedeidati
- Wäre der Nutzungsbedingungen- und Datenschutzrichtlinien-Text auch stattdessen durch #1881 abgedeckt?
   - Lieber Text
- Auf der Anmeldeseite:
  - Auf die Selbstregistrierung welcher Gruppe soll dieser neue Link führen? D.h. in welcher Gruppe bekommt man eine Rolle wenn man sich selber registriert?
      - Alle Anmeldungen fliessen immer in die Gruppe Benutzerkonto. 
  - Was passiert, wenn diese Gruppe die Selbstregistrierung in den Einstellungen deaktiviert, oder gelöscht, archiviert oder fusioniert wird? Muss es einen Fallback geben oder soll dann einfach der Link verschwinden?
      - Sollte nicht passieren. Es sollte niemand ausser Support Zugriff auf die Gruppe haben. Falls doch wäre es schön eine Fehlermeldung zu erhalten. Anschliessend würde es eine Anpassung und Release brauchen.
  - Muss die Gruppe von den SWW-Admins dynamisch auswählbar und änderbar sein?
      - Nein, die Gruppe kann fix bleiben. Link: https://rando-community.ch/de/groups/398/self_registration. 
  - Von all diesen Fragen hängt es ab, ob wir diesen Registrierungs-Link im Core umsetzen können, oder ob das im SWW-Wagon passiert. Das hat dann wiederum grossen Einfluss auf die Umsetzungsstrategie von hitobito/hitobito_sww#102

# ToDo

- [x] Spezifikation in einem neuen Ticket erfassen #117

**Comment by mtnstar** [comment]
alles in https://github.com/hitobito/hitobito_sww/issues/117 zur Umsetzung überführt.
