### ISSUE TITLE
API: Ergänzen von layer_group und role_type

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#104]
Die API soll durch folgende Attribute ergänzt werden:

- [x] Auf der Person die Hauptebene `layer_group`.  Dies entspricht dem Hauptlayer der Person. Dies wird bereits für den CSV Export berechnet.

- [x] Auf der Rolle `role_type` ausgeben. Dies ist die Bezeichnung des Gruppentyp. z.b. Kontakt oder Präsident

**Comment by TheWalkingLeek** [comment]
Soll beim `role_type` die technische Klassifizierung oder die "human-readable" Bezeichnung ausgeliefert werden?
zB: `Group::Geschaeftsstelle::Kassier` vs `Kassier`

**Comment by olibrian** [comment]
Ich würde mich da an der bestehenden API orientieren und `role_type` nehmen. Falls easy machbar können wir auch noch `role_class`  ergänzen.

In der bestehenden API sieht es so aus:
![image](https://user-images.githubusercontent.com/9592347/222386472-fa3e85b1-c404-47b8-8fde-6d15466ff593.png)

**Comment by daniel-illi** [comment]
`layer_group_name` habe ich als "extra attribute" implementiert, da das Berechnen recht aufwändig ist (für jede Person muss ein query gemacht werden).
Das Attribut wird also nur zurückgegeben, wenn explizit im request mit param `?extra_fields[people]=layer_group_name` danach verlangt wird.

Offene Frage: wie integrieren wir jsonapi Erweiterungen der Wagons in die swagger api doku?
