### ISSUE TITLE
PEOPLE: Einmaliger Datenexport mit Personen/FOs mapping für DONMAN

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#112]
Entspricht der Layername immer der FO?

ergänzend zu #48 sollen ein einmaliger Export mit den aktiven Layers einer Person als CSV aus der Produktion gezogen werden.

Mapping Table Person-ID | FO Name

| Hitobito Personen ID | Layer Name        |
|----------------------|-------------------|
| 42                   | Berner Wanderwege |
| 42                  | Zürcher Wanderwege |
| 56467                   | Berner Wanderwege |
| ...                   | ... |

**Comment by olibrian** [comment]
Wird über API gelöst. Kein Export zur Zeit notwendig.
