### ISSUE TITLE
OPS: Staging Umgebung automatisch releasen wenn Prod released wird

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#113]
mit #100 wurde die Staging Umgebung für SWW aufgebaut und auch ein entsprechender Deploy Job. Künftig soll nach dem erfolgreichen Durchlauf des SWW Prod Jenkins jobs, automatisch der staging deploy job getriggert werden.

# Tech-Spec
sowas wie:
```
pipeline {
    agent any

    stages {
        stage ('Whatever') {
            steps {
                    // do something
            }
        }
    }
    post {
        success {
                    build job: 'hitobito_ose3/hit-sww-staging-deploy'
        }
    }
}
```

# Todo

- [ ] Anpassen jenkins prod deployment script: https://gitlab.puzzle.ch/pitc_hit/jenkins_ose3
- [ ] Testen des Prod+Staging deployment während Wartungsfenster

**Comment by olibrian** [comment]
Aktuell wird diese Umgebung manuell bei einem Release angestossen.
