### ISSUE TITLE
PEOPLE: Selbstregistrierung kleinere Anpassungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#119]
Beim testen von der Selbstregistrierung sind noch folgende kleinere Anpassungen aufgefallen. Prio von oben nach unten.

- [x] Sternchen* bei den obligatorischen Felder
- [x] Gemäss Spez #117 soll die Strasse und Nr nicht obligatorisch sein
- [x] Falls es beim eingeben ein Fehler gibt, wird das Feld Strasse und Nummer immer gelöscht. Die anderen ausgefüllten Felder bleiben aber bestehen
- [x] Geburtstag sollte eigentlich korrekterweise Geburtsdatum heissen. Ist dies global so? Falls ja, haben wir hier noch weitere Abhängigkeiten wenn wir hier das Label umbenennen? z.b. API oder Exports? 

Zweite Prio
- [x] Falls ich mich mit einer Mailadresse registriern will, die es schon in Hitobito gibt kommt die Fehlermeldung "Haupt-E-Mail ist bereits vergeben. Diese Adresse muss für alle Personen eindeutig sein, da sie beim Login verwendet wird. Du kannst jedoch unter 'Weitere E-Mails' Adressen eintragen, welche bei anderen Personen als Haupt-E-Mail vergeben sind (Die Haupt-E-Mail kann leer gelassen werden).' -> Passender wäre wohl 'Diese E-Mail-Adresse wird bereits verwendet. Melde Sie sich an oder versuchen Sie eine andere E-Mail-Adresse. Falls Sie das Passwort vergessen haben, können Sie es hier zurücksetzen.'
- [ ] Inputfelder Strasse/Nr und PLZ/Ort sind kürzer als die anderen Felder wie Name
- [x] Anrede (Frau, Mann, Andere) ist nur in Deutsch vorhanden. Hardcoded im Template view: https://github.com/hitobito/hitobito_sww/blob/master/app/views/groups/self_registration/_fields.html.haml#L2. übersetzbar machen!

**Comment by daniel-illi** [comment]
Ich sehe gerade nicht, wie die Fehlermeldung bei "Email taken" gescheit angepasst werden kann.
Die Fehlermeldung soll ja nur im Signup Form anders sein, wir wollen das Verhalten nicht global ändern.

Eine Möglichkeit wäre vielleicht, im `Sww::Groups::SelfRegistrationController` das `#create` zu überschreiben und da nach dem Speichern ein potentielles `entry.errors[:email][:taken]` zu zersetzen mit einem `entry.errors[:email][:signup_taken]` und eine entsprechende Übersetzung zu hinterlegen.

**Comment by daniel-illi** [comment]
Commits zu den erledigten Punkten sind im Core resp. SWW wagon auf dem branch `feature/sww-119-self-reg-form-fixes`

**Comment by olibrian** [comment]
Ticket abgeschlossen ohne offener Punkt (länge der Inputfelder). Falls bedarf besteht das Fomular nochmals grundlegend anzupassen, kann ein neues Ticket erstellt werden.
