### ISSUE TITLE
IMPORT: sww_cms_profile_id nachladen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#124]
Mail von Cloudtec

> Der GoLive von der neuen Schweizer Wanderwege ist soweit problemlos über die Bühne und wir sind nun live!
> Bei einigen Benutzerkonten ist nun jedoch das Problem aufgetreten, dass bspw. die selbstgeplanten Wanderungen nicht mitgekommen sind. Diese ordnen wir ja mit der alten Benutzerkonto-ID welche ihr mit dem Import hinterlegt habt zu. Nun zwei der User sind Thomas Gloor und Tatjana Häuselmann von SWW. Kann es sein, dass ihr bei bereits existierenden Usern die Benutzerkonto-ID nicht hinterlegt habt? Wir haben bei diesen beiden keine erhalten.

Habe kurz nachgeschaut und bei Thomas Gloor (ID 902) und Tatjana (ID 1043) ist keine alte sww_cms_profile_id hinterlegt. Die Personen waren schon mit der Mailadresse in Hitobito. Daher wurden diese nicht nochmals importiert.

Den bestehenden Personen soll noch die sww_cms_profile_id nachgeladen werden. Dies wenn wir die gleiche Mailadresse in Hitobito wie auf der alten Benutzerkonto haben.

**Comment by daniel-illi** [comment]
Ich habe die sww_cms_profile_id importiert.
