### ISSUE TITLE
FOOTER: Ausbleden bei der Anmeldung via OAUTH

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#125]
Der Footer wurde durch https://github.com/hitobito/hitobito_sww/commit/6842c4cbabd2a346b81b6c54156fa1b0f57e5809 ausgeblendet.

Dies scheint bei der Anmeldung via OAUTH noch nicht zu funktionieren.

![image](https://user-images.githubusercontent.com/9592347/228647684-dcdefb40-cd2c-45ce-b067-7dd201387ed9.png)

Im Core:

- '> Pfeil' vor Versionsnr für collapse Funktion core/wagon info
- Standardmässig ist nur Pfeil und Versionsnr sichtbar
- Beim Click auf > Pfeil werden Infos collapsed
- Auskommentierten Footer im SWW Wagon wieder reinnehmen

# ToDo

- [ ] https://github.com/hitobito/hitobito/blob/master/app/views/layouts/oauth.html.haml#L42 footer entfernen

**Comment by mtnstar** [comment]
auch in layouts/oauth.html.haml rausnehmen. (sww wagon)

**Comment by mtnstar** [comment]
![image](https://user-images.githubusercontent.com/655627/229795648-abd457ac-94d7-4627-9db1-a6c10af0b725.png)

beim oauth login form ist der footer noch drinn
