### ISSUE TITLE
LABEL: Haupt-E-Mail in E-Mail ändern

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#126]
Können wir für die SWW Instanz das Label von der Haupt E-Mail umbenennen?

Ist: `Haupt-E-Mail` 
Soll: `E-Mail`

**Comment by mtnstar** [comment]
Im Core mal in den Translations umbenennen. Falls keine tests failen, so übernehmen.
Grundsätzlich scheint Haupt- etwas redundant. E-Mail wäre gut und kann von Weitere E-Mails unterschieden werden.
sonst einfach nur im SWW wagon anpassen.
