### ISSUE TITLE
INVOICES: Stornierte Rechnung auf Buchungsbeleg

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#136]
Wird eine Rechnung storniert so erscheint diese aktuell noch immer in der Übersicht "Buchungsbeleg" und zählt dort auch zur Anzahl der Rechnungen.

![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/099d206f-a188-45e0-b049-ac98e1bd6af6)

![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/46058f65-7f99-442f-9b57-2df16dc9cf4d)

Neu sollen Rechnungen mit dem Status "Storniert" nicht mehr in der Übersicht "Buchungsbeleg auftauchen. Sie sollen weder bei der Anzahl noch zum Betrag bezahlt dazugezählt werden.

Auch in der Übersicht "Rechnungen zu Artikel xy" auf welche man kommt wenn auf man auf eine der Produktbezeichnungen klickt   sollen die stornierten Rechnungen anschliessend nicht mehr auftauchen.

Prüfung: Umsetzung im Core? Wie ist hier der Usecase und die Wünsche anderer Kunden welche Rechnungen in Hitobito versenden?

# Tech-Spec

- Umsetzung im Core
- https://github.com/hitobito/hitobito/blob/master/app/controllers/invoices/evaluations_controller.rb
- https://github.com/hitobito/hitobito/blob/master/app/domain/invoice/item_evaluation.rb

# ToDo

- [x] Bestehende unit tests mit stornierten Rechnungen ergänzen
- [x] Code anpassen sodass stornierte Rechnungen weder beim Betrag noch bei der Anzahl mitgezählt werden
- [x] CHANGELOG entry
- [x] Manuell Testen

**Comment by ThomasEllenberger** [comment]
Evtl. https://github.com/hitobito/hitobito/issues/1691 gleich mit lösen.
