### ISSUE TITLE
PEOPLE: Neuregistrierung - Angabe des Landes

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#140]
Bei der externen Registrierung zu einer Gruppe wird aktuell das Feld "Land" nicht angezeigt und kann entsprechend nicht ausgefüllt werden.

Beispiel: https://rando-community.ch/de/groups/398/self_registration
![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/9ed5e774-08ad-4286-bb73-b2e17809dec2)

Neu soll das Feld "Land" bei einer Neuregistrierung auch ausgefüllt werden können.

Standardmässig ist Schweiz vorausgewählt

# Tech-Spec

- Umsetzung im SWW Wagon
- https://github.com/hitobito/hitobito_sww/blob/master/app/views/groups/self_registration/_fields.html.haml

# ToDo

- [x] https://github.com/hitobito/hitobito_sww/blob/master/app/controllers/sww/groups/self_registration_controller.rb#L20 rename to address_form_params? or is it by intention called from?
- [x] Country Feld ergänzen, übersetzung sicherstellen, Gleiches Typeahead DropDown wie bei Person#edit
- [x] CHANGELOG Eintrag
- [x] Manuell testen

**Comment by carlobeltrame** [comment]
Das Selbstregistrierungsformular hat bisher im Core bewusst sehr wenige Felder, und wir ergänzen jeweils in den Wagons, wenn ein Feld im Wagon obligatorisch ist. Die Adresse ist bisher nicht im Selbstregistrierungsformular im Core vorhanden. Die Adresse und das Land im Core zu ergänzen wäre daher ein Grundsatzwechsel, den wir zuerst mit den anderen Verbänden absprechen müssten. Zusätzlich wären auch Änderungen an anderen Wagons nötig, welche die Adresse bereits eingefügt haben. Daher sehe ich für dieses Ticket erst mal die Umsetzung im Wagon vor.
