### ISSUE TITLE
EVENT: Mehrsprachigkeit

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#204]
Als Erfasserin oder Erfasser eines Anlasses möchte ich gewisse Inhalte mehrsprachig befüllen können. Aktuell gerne deutsch und französisch. Die Übersetzungen müssen optional sein. Die Hauptsprache soll als Fallback dienen, falls die Zweitsprache nicht oder nur teilweise ausgefüllt ist.

Folgende Felder müssen mindestens übersetzbar sein:
- Name
- Beschreibung
- Ort / Adresse
- Anmeldeangaben

**Comment by ThomasEllenberger** [comment]
Name, Beschreibung und die Fragen und Antworten in den Anmeldeangaben können bereits heute Übersetzt werden.
Offen: Ort/Adresse

**Comment by ThomasEllenberger** [comment]
Closed, da die meisten Übersetzungen bereits vorhanden sind.
