### ISSUE TITLE
PEOPLE: Personen ohne Rollen löschen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sww#213]
Es sollen einmalig sämtliche Personen in der Gruppe https://rando-community.ch/de/groups/45/deleted_people gelöscht werden.
Siehe auch: https://help.puzzle.ch/#ticket/zoom/8124

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
Die Personen wurden am 2024-09-28 bereits gelöscht, dieses Issue hier habe ich komplett übersehen.

**Comment by kronn** [comment]
Ich habe die Personen ohne Rollen, die zuletzt in der genannten Gruppe waren, gelöscht. Alle verbundenen Daten sind aus dem System entfernt.
