### ISSUE TITLE
Grundpaket: Produktionsumgebung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#3]
Domain: rando-community.ch

Vorbereitung der produktiven Umgebung

- [x] mailkonten
- [x] composition-repo um production-branch erweitern
- [x] jenkins-job
- [x] Credentials im Cryptopus
- [x] DNS
- [x] APPUiO-Projekt anlegen
- [x] labels setzen
- [x] initial-setup mit cia (https://wiki.puzzle.ch/Hitobito/ProjektSetup)
- [x] kustomize-overlay
- [x] apply-config
- [x] Monitoring (https://docs.puzzle.ch/guides/latest/ruby-rails-user-guide/index.html#_monitoring_einrichten)

See: #1

**Comment by TheWalkingLeek** [comment]
Da die domain noch nicht vorhanden ist, müssen ein paar Dinge dann noch erledigt werden:
kustomize-overlay:
    - [ ] RAILS_HOST_NAME mit domain anpassen
    - [ ] ingress.yml external route einfügen
- Monitoring:
    - [ ] HTTP-Monitoring einrichten

**Comment by olibrian** [comment]
DNS ist jetzt bekannt: rando-community.ch
Loic reserviert noch den Eintrag. @olibrian sendet ihm die notwendige Konfigruation.
