### ISSUE TITLE
INVOICE: Export Buchungsbeleg

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#39]
Als Kassier
möchte ich ein Buchungsbeleg exportieren können,
um die Zahlungen in die Buchhaltung zu übertragen

Der Buchungsbeleg soll folgende Informationen enthalten:

![Buchungsbeleg](https://user-images.githubusercontent.com/9592347/164710392-d7dfa18f-c9b1-4e2b-9e4c-d5e56395879e.png)

Das Periode kann entsprechend gewählt werden.
Die Beträge sollen aufgrund der Zahlungen der Periode berechnet werden.

Umsetzung als Reporting im WebUI als Table
Zuweisung Payment -> Rechnungsartikel könnte noch speziell werden, da wir das in der DB nicht abbilden. Müsste man also korrekt “interpretieren”.
Sicher nicht unmöglich, muss aber gut getestet werden.

Export in Ticket: #61

# Mockup

See hitobito/hitobito#1787

# Tech-Spec

Umsetzung soweit verallgemeinerbar im Core.

- [x] Neuer Eintrag "Auswertungen" im Rechnungen-Menü jedes Layers (linke Navigation, siehe Mockup)
- [x] Auf diesem neuen Auswertungen-Sheet werden in Zukunft z.B. in Tabs verschiedene Auswertungen abrufbar werden. Für den Moment reicht es aber wenn der Buchungsbeleg direkt ohne Tabs angezeigt wird
- [x] Datumsbereich als Inputfelder mit Submit-Button
  - [x] Standard ist von "vor einem Monat" bis "heute"
- [x] Zeilen "Verbandslösung Schweizer Wanderwege", "Druckdatum", "Mitarbeiter" vom Mockup können weggelassen werden
- [x] Tabelle wird berechnet aus den _vollständigen_ Zahlungen im Datumsbereich in diesem Layer
  - [x] Da nur vollständig bezahlte Rechnungen betrachtet werden, können die Rechnungsartikel einfach summiert werden.
  - [x] Die letzte Zeile ist immer "Überschuss" (excess) was im SWW-Wagon mit "Spenden" übersetzt werden soll
- [x] Allenfalls Domainklasse `Donation` auf `Payments` oder `PaymentCollector` o.ä. umbenennen und ggf. anpassen
  - [x] in allen Wagons prüfen, ob das noch woanders verwendet wird
- [x] Da die Rechnungsposten nach Namen gruppiert werden müssen, müsste man möglicherweise einen DB-Index auf invoice_items.name machen. Dies sollte aber kurz getestet werden (sowohl mit kurzen wie mit langen Datumsbereichen). Nicht in jedem Fall ist ein Index besser als keiner.
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kebpot** [comment]
![grafik](https://user-images.githubusercontent.com/95677081/172825973-814c7d91-f12f-4f5e-a2b3-83fedca83723.png)

-  Es sollten alle Zahlungen berücksichtig werden. Aus solche welche nicht vollständig bezahlt wurden. 
- Unterzahlungen sollten ebenfalls ausgewiesen werden (= fehlender Betrag), berechnet aus differenz zwischen offenem Betrag und Zahlung pro Rechnung. Dieser Betrag sollte nicht in das Total einfliessen (dient der Info/ Übersicht).

- Anstatt Umsetzung in Navigation Links wäre uns eine Umsetzung im Export Button lieber. 
![grafik](https://user-images.githubusercontent.com/95677081/172826588-14f4dfa4-3322-4581-81f5-237539e105f0.png)

- Ideal wäre wenn man den Daterange direkt in der Rechnungsübersicht einschränken könnte. Damit wären zwei Issues auf einmal gelöst. Der Export (Buchungsbeleg) wäre dann jeweils für die Selektion. 
![grafik](https://user-images.githubusercontent.com/95677081/172826802-3ccfd300-2084-4205-8980-3fffa3b53802.png)

**Comment by kebpot** [comment]
Das Buchungsbeleg sollte alle Zahlungen innerhalb des Daterange greifen - sowohl für Einzel- wie auch Sammelrechnungen.

**Comment by kebpot** [comment]
" Datumsbereich als Inputfelder mit Submit-Button
 Standard ist von "vor einem Monat" bis "heute""
Für den Daterange sollte eine Auswahl möglich sein wonach gefiltert wird (Erstellt, bezahlt, ...)

**Comment by olibrian** [comment]
Annahme/Umsetzung:
* Unterzahlung auch ins Total aufnehmen -> Ansonsten stimmt der Buchungsbeleg nicht mit dem Bankauszug überein.
* Umsetzung erfolgt in einem Web-UI. Export erfolgt in #61

**Comment by TheWalkingLeek** [comment]
Bereits erledigt:
-  `Donation` Methoden:
  - `from` & `to`: Um die Daterange anzugeben
  -  `grouped_by_invoice_items`: Um die Tabellendaten heraus zu ziehen
  -  `of_fully_payed_invoices`: Filtert Payments heraus, die nicht eine Rechnung ausreichend abbezahlt hat. Wichtig ist, dass wenn mehrere Payments zu derselben Rechnung besagte Rechnung gemeinsam abbezahlen, bleiben alle Payments erhalten.
- Controller Endpunkt mit grundlegender View & Daterange Pickern
- Beginn Ausgabe der erfordeten Werte innerhalb des Controllers (sicher nicht ideal): Das Total per Rechnungsposten ist noch nicht korrekt!!! Bei mehreren Payments pro Rechnung wird es noch falsch berechnet.

ToDo:
Siehe ToDo im Ticket.
Sicher auch noch eine Aufräumaktion bisher bestehender Sachen, insbesondere Controller hab ich so das Gefühl :)

Bei inhaltlichen Fragen gerne an @olibrian wenden

Weiterführende Ideen:
- Bei Unterzahlungen (evtl. auch Überzahlungen) in einer weiteren Tabelle  die Zahlungen und/oder dazugehörigen Rechnungen anzeigen. So ist klarer, woher die Über-/Unterzahlungen stammen

**Comment by kebpot** [comment]
@TheWalkingLeek 
Aktuell hat es noch keine Export Funktion? Der Buchungsbeleg sollte via .xlsx exportiert werden können. siehe Kommentar 9. Juni. 

Auf dem Beleg werden Teilzahlungen ausgewiesen, allerdings wird der bezahlte Betrag errechnet und nicht der fehlende Betrag.  Wir möchten wissen wie gross die Differenz ist. In diesem Fall wurde CHF 50.00 von einer Rechnung über CHF 75.00 bezahlt. Es fehlen also CHF 25.00. 


![image](https://user-images.githubusercontent.com/95677081/183042434-8de9745a-ec1e-4248-a13d-1c5a6a129ca7.png)

**Comment by carlobeltrame** [comment]
Der Export folgt im Ticket #61, siehe Kommentar 5. Juli. Hier wurden erst mal die Grundlagen gelegt.
Zur Unterzahlung weiss ich noch nicht was der aktuelle Stand ist, besprechen wir morgen wenn @TheWalkingLeek wieder da ist.
