### ISSUE TITLE
TECH: Test Setup OIDC für Cloudtech, Unterstützung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#54]
damit Cloudtech OIDC Implementieren kann, wird ein Testaccount auf der Integrationsumgebung eingerichtet.
Falls Cloudtech noch Unterstützung bei der Implementation benötigt kann dies ebenfalls auf dieses Ticket gebucht werden.

**Comment by olibrian** [comment]
Zugang soweit eingerichtet
