### ISSUE TITLE
PEOPLE: Attribute OIDC / Rollen CMS Benutzer

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#76]
# OpenID Connect Attribute

Im Moment werden folgende Personen Attribute per OIDC zur Verfügung gestellt:

![image](https://user-images.githubusercontent.com/655627/191706284-08eb35f6-0e1a-49ba-917f-6ffa7e270b4e.png)

Ergänzend sollen hier noch folgende Attribute hinzugefügt werden:

- gender
- company_name falls eine Firma und kein first_name/last_name gesetzt ist

# Gruppe / Rollen für CMS Benutzer

CMS Benutzer benötigen eine Gruppe bzw. Rolle in Hitobito damit sich diese einloggen können:

- Neuer Gruppentyp sowie Gruppe auf unterhalb Root-Layer für CMS Benutzer
- Neue Rolle innerhalb dieser Gruppe

**Comment by olibrian** [comment]
Neue Gruppe für CMS Benutzer wurde im #82 umgesetzt. Attribute passen fürs erste soweit.
