### ISSUE TITLE
PEOPLE: Authentifizierung mit legacy CMS password hash

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#85]
Bestehender CMS Benutzer meldet sich erstmalig an Hitobito an:
  1. Passwort wird geprüft mit legacy cms password hash und salt
  2.  Falls authentifizierung erfolgreich, wird mit dem Klartextpasswort gleich ein State of the art Devise Password hash erstellt. Ab diesem Zeitpunkt verwendet der Benutzer den gleichen auth-mechano wie alle anderen Benutzer.
  3. der nicht mehr benötigte legacy password salt auf der Person wird gelöscht
  4. Erneute Authentifizierung (ohne das der Benutzer dies mitkriegt) mit dem State of the art Devise Password hash um sicherzustellen das die Authentifizierung erfolgreich war
  5. Benutzer wird angemeldet

Können sich migrierte Benutzer nicht an Hitobito anmelden (z.b. weil kein oder SHA1 password hash), soll eine entsprechende Meldung angezeigt werden mit der Aufforderung ein neues Passwort zu setzen:

'Lieber Benutzer, dein Account wurde auf ein neues System gezügelt. Leider konnte dein Passwort aus Sicherheitsgründen nicht übernommen werden. Bitte setzte ein neues Password (link)'

# Tech-Spec

Folgende Funktion wurde im alten CMS benutzt um ein Salted Password zu generieren:
```php
static public function getSaltedPassword($password, $salt) {
  return md5($salt . self::PEPPER . $password . self::PEPPER . $salt);
} 
```
* $password: Klartextpassword des users
* $salt: Wert aus Spalte profile_password_salt
* self::PEPPER: im Login Script fix hinterlegter Wert (im Cryptopus abgelegt)
* mit '.' lassen sich in PHP strings konkatinieren, sprich ist einfach die kombi von den Variablen oben: salt+pepper+password+pepper+salt

Implementation mit ruby (fake werte, richtige hash/pw Werte der Redaktion bekannt)
```ruby
pw_hash = '$2y$12$9qlUdz1cVFbLGS0vgaW7ttZx1Ggg4GdBB01G6Ehe7Jw2rtecossb9'
pepper = 'abcd42%'
password = 'hito42bito'
salt = 'a9042dca3fe4bbba164999cd945b9dd8'
salted_password = salt + pepper + password + pepper + salt
g = BCrypt::Password.new(pw_hash)
g == salted_password
```

# ToDo

- [ ] Wichtig: erst prüfen ob mit einem bestehenden Salt/Pepper/Hash/Password Kombi in Ruby so überprüft werden kann. ein erster Versuch beim Konzipieren dieses Issues hatte leider nicht funktioniert. Vermutlich stimmt aber das uns vorliegende Passwort nicht. Am besten neuen Benutzer registrieren im bestehenden CMS, dann DB dump organisieren und mit den Werten prüfen.
- [ ] Erweiterung Devise im sww wagon

**Comment by carlobeltrame** [comment]
Upgraden von Passwörtern bei erstmaligem Login:
https://stackoverflow.com/a/9079088

**Comment by olibrian** [comment]
Gemäss https://github.com/hitobito/hitobito_sww/issues/103#issuecomment-1443853470 keine weiteren Anpassungen notwendig.
