### ISSUE TITLE
EVENTS: Warteliste auf Events aktivieren

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#88]
In der SWW Umgebung sollen auf Event (Anlässe) die Warteliste erweitert werden. Der Benutzer soll wählen können ob die Warteliste aktiv ist oder nicht.

### Tech spec
- Umsetzung im SWW Wagon
- Analog zu SJAS: https://github.com/hitobito/hitobito_sjas/issues/27
- Umgesetzte Änderungen im SJAS-Wagon https://github.com/hitobito/hitobito_sjas/commit/5df5d88852b830521d18e1f5be605a61d255af0a
  - Danach wurden noch Verbesserungen basierend auf dem SJAS-Feedback gemacht, aber soweit ich sehe nur [im Core](https://github.com/hitobito/hitobito/commit/25179e4e111627bb75bec528a7777a0eb0e83b95), daher hier nicht weiter relevant

### TODO
- [ ] Änderung analog zu [Änderung bei SJAS](https://github.com/hitobito/hitobito_sjas/commit/5df5d88852b830521d18e1f5be605a61d255af0a) umsetzen

**Comment by olibrian** [comment]
Wenn ich mich zu einem Event anmelde, erhalte ich die Meldung: "Es wurde eine Voranmeldung für Teilnahme von Olivier Brian in Anlass 836 erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden."
Dies ist unabhängig ob es eine Warteliste gibt oder nicht.

**Comment by kronn** [comment]
Hier scheint noch nicht der richtige Code-Stand auf der Integration gewesen zu sein. Bei meinem Test hat es jetzt funktioniert. Ich schliesse das Issue hier erstmal.
