### ISSUE TITLE
DATENBEREINIGUNG: Unnötige Zeilenunbrüche in der Adresse entfernen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#89]
Einige Adressen haben einen Zeilenumbruch und anschliessend ein Leerschlag (Beispiel: https://rando-community.ch/de/groups/74/people/14106).
Der unnötige Zeilenumbruch und der Leerschlag sollte auf sämtlichen Adressen entfernt werden.

**Comment by carlobeltrame** [comment]
Generell passiert das auf allen Feldern automatisch, immer wenn eine Person gespeichert wird. Die fehlerhaften Einträge kommen von einem Datenimport her.
Ich habe das jetzt einmalig auf Integration und Produktion für alle Personen und nur beim Adress-Feld gefixt. Dazu habe ich folgenden Befehl auf der Konsole abgesetzt:
```ruby
Person.find_each { |p| p.update_column(:address, StripAttributes.strip_string(p.address)) }
```
Bei rund 33000 Personen hat das ca. 3 Minuten gedauert.
