### ISSUE TITLE
API: Ergänzen von zusätzlichen Attributen auf Person

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#93]
Die neue JSON Api für Personen soll durch folgende Attributen der Person ergänzt werden:

- [x] updated_by 
- [x] update_at

### Tech spec
Umsetzung im SWW Wagon

### TODO
- [x] In https://github.com/hitobito/hitobito_sww/blob/master/app/resources/sww/person_resource.rb `updated_at` ergänzen, `writable: false`
- [x] An demselben Ort `updated_by` ergänzen, als [`belongs_to`](https://www.graphiti.dev/guides/concepts/resources#belongs-to), `writable: false`, und nur `readable` falls `can?(:show, model_instance.updated_by)` (siehe Beispiel für solche Checks im [Core](https://github.com/hitobito/hitobito/blob/master/app/resources/person_resource.rb#L46))

**Comment by daniel-illi** [comment]
Entgegen dem Beispiel im description TODO ist es auf einer resource relation nicht möglich, das `writable` dynamisch zu setzen (abhängig von der ability).
Graphiti unterscheidet bei dieser Option nur zwischen `false` und `truthy`, es wird kein Methodencall gemacht mit dem gesetzten Symbol (anders als bei den resource attribute).

Siehe: https://github.com/graphiti-api/graphiti/blob/61181e72fdb2d2d5a74d430df41bb2fe0aa7f654/lib/graphiti/resource/dsl.rb#L204

Dies funktioniert also auch bei den existierenden resourcen im Core nicht!

**Comment by daniel-illi** [comment]
Ein erster Teil ist bereits in den master gemergt.
Der Rest depends on hitobito/hitobito#1926, wenn dieses gemergt ist werde ich hier rebasieren und anpassen.
